const dataMataPelajaran = [
  {
    judul: 'Matematika',
    penulis: 'John Doe',
    penerbit: 'Penerbit A',
    tahun: 2020,
    stok: 10,
  },
  {
    judul: 'Bahasa Inggris',
    penulis: 'Jane Smith',
    penerbit: 'Penerbit B',
    tahun: 2019,
    stok: 5,
  },
  {
    judul: 'Fisika',
    penulis: 'Albert Einstein',
    penerbit: 'Penerbit C',
    tahun: 2021,
    stok: 8,
  },
  {
    judul: 'Kimia',
    penulis: 'Marie Curie',
    penerbit: 'Penerbit D',
    tahun: 2018,
    stok: 12,
  },
  {
    judul: 'Biologi',
    penulis: 'Charles Darwin',
    penerbit: 'Penerbit E',
    tahun: 2022,
    stok: 7,
  },
  {
    judul: 'Sejarah',
    penulis: 'William Shakespeare',
    penerbit: 'Penerbit F',
    tahun: 2017,
    stok: 15,
  },
  {
    judul: 'Geografi',
    penulis: 'Isaac Newton',
    penerbit: 'Penerbit G',
    tahun: 2023,
    stok: 20,
  },
  {
    judul: 'Ekonomi',
    penulis: 'Adam Smith',
    penerbit: 'Penerbit H',
    tahun: 2016,
    stok: 6,
  },
  {
    judul: 'Seni',
    penulis: 'Pablo Picasso',
    penerbit: 'Penerbit I',
    tahun: 2024,
    stok: 3,
  },
  {
    judul: 'Olahraga',
    penulis: 'Michael Jordan',
    penerbit: 'Penerbit J',
    tahun: 2015,
    stok: 9,
  },
  {
    judul: 'Teknologi Informasi',
    penulis: 'Bill Gates',
    penerbit: 'Penerbit K',
    tahun: 2025,
    stok: 4,
  },
  {
    judul: 'Psikologi',
    penulis: 'Sigmund Freud',
    penerbit: 'Penerbit L',
    tahun: 2014,
    stok: 11,
  },
  {
    judul: 'Sosiologi',
    penulis: 'Emile Durkheim',
    penerbit: 'Penerbit M',
    tahun: 2013,
    stok: 2,
  },
];

export default dataMataPelajaran;
