const dataRiwayatPeminjaman = [
  {
    id: 1,
    nama: 'John Doe',
    buku: 'Pengantar Ilmu Komputer',
    tglPinjam: '2025-05-01',
    tglKembali: '2025-05-08',
    jumlah: 1,
    status: 'Dipinjam',
  },
  {
    id: 2,
    nama: 'Jane Smith',
    buku: 'Matematika Lanjutan',
    tglPinjam: '2025-04-25',
    tglKembali: '2025-05-02',
    jumlah: 2,
    status: 'Dikembalikan',
  },
  {
    id: 3,
    nama: 'Ahmad Fauzi',
    buku: 'Fisika Dasar',
    tglPinjam: '2025-05-02',
    tglKembali: '2025-05-09',
    jumlah: 1,
    status: 'Dipinjam',
  },
  {
    id: 4,
    nama: 'Siti Aminah',
    buku: 'Kimia Organik',
    tglPinjam: '2025-04-28',
    tglKembali: '2025-05-05',
    jumlah: 1,
    status: 'Dikembalikan',
  },
  {
    id: 5,
    nama: 'Budi Santoso',
    buku: 'Biologi SMA',
    tglPinjam: '2025-05-03',
    tglKembali: '2025-05-10',
    jumlah: 3,
    status: 'Dipinjam',
  },
  {
    id: 6,
    nama: 'Rina Lestari',
    buku: 'Sejarah Indonesia',
    tglPinjam: '2025-04-29',
    tglKembali: '2025-05-06',
    jumlah: 2,
    status: 'Dikembalikan',
  },
  {
    id: 7,
    nama: 'David Wijaya',
    buku: 'Bahasa Inggris Aktif',
    tglPinjam: '2025-05-04',
    tglKembali: '2025-05-11',
    jumlah: 1,
    status: 'Dipinjam',
  },
  {
    id: 8,
    nama: 'Lina Marlina',
    buku: 'Geografi untuk SMA',
    tglPinjam: '2025-05-01',
    tglKembali: '2025-05-08',
    jumlah: 2,
    status: 'Dipinjam',
  },
  {
    id: 9,
    nama: 'Agus Salim',
    buku: 'Ekonomi Mikro',
    tglPinjam: '2025-04-27',
    tglKembali: '2025-05-04',
    jumlah: 1,
    status: 'Dikembalikan',
  },
  {
    id: 10,
    nama: 'Nurul Huda',
    buku: 'Sosiologi Dasar',
    tglPinjam: '2025-05-05',
    tglKembali: '2025-05-12',
    jumlah: 3,
    status: 'Dipinjam',
  },
];

export default dataRiwayatPeminjaman;
